CREATE TABLE IF NOT EXISTS companies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(120) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  brand_name VARCHAR(120) NULL,
  brand_color VARCHAR(9) NOT NULL DEFAULT '#2563eb',
  logo_url VARCHAR(500) NULL,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company_id INTEGER NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  lang VARCHAR(5) NOT NULL DEFAULT 'fr',
  active INTEGER NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS vehicles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  plate VARCHAR(40) NOT NULL DEFAULT '',
  imei VARCHAR(32) NOT NULL UNIQUE,
  token VARCHAR(40) NOT NULL,
  speed_limit INTEGER NOT NULL DEFAULT 80,
  lat DOUBLE NULL,
  lng DOUBLE NULL,
  speed INTEGER NOT NULL DEFAULT 0,
  heading INTEGER NOT NULL DEFAULT 0,
  acc INTEGER NOT NULL DEFAULT 0,
  fuel DOUBLE NULL,
  temp DOUBLE NULL,
  online INTEGER NOT NULL DEFAULT 0,
  cut INTEGER NOT NULL DEFAULT 0,
  last_update BIGINT NULL,
  static_since BIGINT NULL,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS positions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  vehicle_id INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  lat DOUBLE NOT NULL,
  lng DOUBLE NOT NULL,
  speed INTEGER NOT NULL DEFAULT 0,
  t BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_positions_vehicle_t ON positions (vehicle_id, t);
CREATE INDEX IF NOT EXISTS idx_positions_t ON positions (t);

CREATE TABLE IF NOT EXISTS geofences (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  lat DOUBLE NOT NULL,
  lng DOUBLE NOT NULL,
  radius INTEGER NOT NULL,
  on_enter INTEGER NOT NULL DEFAULT 1,
  on_exit INTEGER NOT NULL DEFAULT 1,
  cut_on_exit INTEGER NOT NULL DEFAULT 0,
  speed_limit INTEGER NULL
);

CREATE TABLE IF NOT EXISTS alerts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company_id INTEGER NOT NULL,
  vehicle_id INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  type VARCHAR(30) NOT NULL,
  detail VARCHAR(255) NOT NULL DEFAULT '',
  lat DOUBLE NULL,
  lng DOUBLE NULL,
  t BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_alerts_company_t ON alerts (company_id, t);
CREATE INDEX IF NOT EXISTS idx_alerts_vehicle_t ON alerts (vehicle_id, t);

CREATE TABLE IF NOT EXISTS commands (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company_id INTEGER NOT NULL,
  vehicle_id INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  user_id INTEGER NULL,
  command VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'sent',
  t BIGINT NOT NULL
);
